defaults: &defaults
  app:
    title: XManager
  menus:
    administrators:
      -
        - "users"
        - "/users"
    product_owners:
      - 
        - "team_members"
        - "/team_members"
      -
        - "product_backlogs"
        - "/product_backlogs"
      -
        - "project_plannings"
        - "/project_plannings"
      -
        - "sprint_backlogs"
        - "/sprints/on_air"
      -
        - "burndown_charts"
        - "/burndown_charts"

    scrum_masters: 
      -
        - "product_backlogs"
        - "/product_backlogs"
      -
        - "project_plannings"
        - "/project_plannings"
      -
        - "sprint_backlogs"
        - "/sprints/on_air"
      -
        - "burndown_charts"
        - "/burndown_charts"

    developers:
      -
        - "product_backlogs"
        - "/product_backlogs"
      -
        - "project_plannings"
        - "/project_plannings"
      -
        - "sprint_backlogs"
        - "/sprints/on_air"
      -
        - "burndown_charts"
        - "/burndown_charts"

production:
  <<: *defaults

development:
  <<: *defaults

test:
  <<: *defaults
