defaults: &defaults
  app:
    title: XManager
  menus:
    administrators:
      -
        - "users"
        - "/users"
    product_owners:
      - 
        - "user_stories"
        - "/backlogs"
      -
        - "new_user_story"
        - "/backlogs/new"
      -
        - "tasks"
        - "/tasks"
      -
        - "new_task"
        - "/tasks/new"
      -
        - "user_roles"
        - "/project_roles"

    scrum_masters: 
      - 
        - "user_stories"
        - "/backlogs"
      -
        - "new_user_story"
        - "/backlogs/new"
      -
        - "tasks"
        - "/tasks"
      -
        - "new_task"
        - "/tasks/new"
      -
        - "user_roles"
        - "/project_roles"

    developers:
      - 
        - "user_stories"
        - "/backlogs"
      -
        - "new_user_story"
        - "/backlogs/new"
      -
        - "tasks"
        - "/tasks"
      -
        - "new_task"
        - "/tasks/new"
      -
        - "user_roles"
        - "/project_roles"

production:
  <<: *defaults

development:
  <<: *defaults

test:
  <<: *defaults
